### ISSUE TITLE
Client misbehaves when server has TrackMessageSizeInterceptor and trackMessageLength=false

### ISSUE THREAD

**Issue by ookke** [Atmosphere/atmosphere#1848]
Just wasted a few hours debugging the following scenario, hopefully I can save someone else some time:

Serverside is implemented using ManagedService which enables TrackMessageSizeInterceptor by default. 

The atmosphere javascript client on the other hand had the default trackMessageLength=false setting.

This causes _handleProtocol() to attempt parsing the client heartbeat interval from the wrong messages[] index, parsing random numbers out of the connection uuid string. This can result in the client sending heartbeats in a 4 ms loop for example.

Wouldn't it make sense for the default settings to match each other, and/or for the client to not try to parse the heartbeat interval out of an uuid string?

Using Atmosphere 2.2.5 and websocket transport.

**Comment by jfarcand** [comment]
@ookke How can this be achieved? Pull request welcomed so I can play with your idea. Thanks!

**Comment by ookke** [comment]
I can reproduce it for example with the chat sample, just change clientHeartbeatFrequencyInSeconds to 0 in web.xml and trackMessageLength to false in application.js. You might have to refresh the chat page a few times to get lucky with a uuid that can be parsed into an int, but eventually you'll see the client making up a random client heartbeat interval.

**Comment by jfarcand** [comment]
@ookke OK. My question is how can this be fixed as the '|' (the delimiter) can be used by the application as well.

**Comment by ookke** [comment]
I'm not very closely familiar with Atmosphere internals, but perhaps the client and server could compare settings during the connection initialization phase to ensure that they are compatible?

**Comment by jfarcand** [comment]
Won't fix as this will require protocol change. Maybe in 3.0.0

**Comment by lw-mcno** [comment]
The described one is not the only side effect of this misconfiguration.

When using long-polling, the (initial) message-length (in my case always 41) is parsed as the uuid, so that all the clients use the uuid 41 instead of what the server generated for them (which doesn't work).

Maybe there be a warning in the JavaScript-client when the parsed number doesn't look uuid-y?

**Comment by jfarcand** [comment]
@lw-mcno You have a setup issue. Please post your application on the mailing list with details: https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by lw-mcno** [comment]
@jfarcand Thanks for the fast answer.
I've had a setup issue where @ManagedService (and thus TrackMessageSizeInterceptor) was used and trackMessageLength was set to false. The parsed uuid with long polling was always "41". After correcting the configuration everything is OK (the uuids from the server are re-used on new requests), but it would have been helpful if the client warned of such a situation, for example by examining the uuid before parsing and that's why I've written it as a comment on this bug.

Example first response:
41|a08188e8-e398-4d7f-96c1-8dd9b6d24d5c|0|X|

So without trackMessageLength the length (41) is parsed instead of the uuid and the uuid (a08188e8-e398-4d7f-96c1-8dd9b6d24d5c) is parsed instead of the heartbeat interval, etc.
