### ISSUE TITLE
[Performance] Add Support for ForkJoinPool when jdk7+ is used

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1972]

**Comment by slovdahl** [comment]
As always, I'm late to the party :grin: But I just want to document my findings.

Until recently we had been using 2.2.x, but now that we upgraded to 2.7.x, it turns out that this actually caused a performance regression in some of our use cases.

Sometimes, we have a lot of (mostly WebSocket) clients connecting simultaneously (10k+), and some handshake traffic going over the wire immediately after the connection has been established. With 2.2.x this has always worked fine (assuming there's enough resources on the server). With 2.7.x on the other hand, we started seeing big delays in delivering the initial handshake from the server side to the client. We monitor the connection on both sides, and after 30-60 seconds close/try to reestablish connections if they have timed out, and this is actually what happened here. Using Jetty 9.

After reverting back to the old behaviour by setting `org.atmosphere.useForkJoinPool = false`, everything went back to normal.

**Comment by jfarcand** [comment]
@slovdahl Probably the pool is not configured properly? I means the default is probably wrong for your use case.

**Comment by slovdahl** [comment]
Might be yeah, but how would one configure it? :thinking: AFAICT there are no settings for the fork join pool. If `org.atmosphere.cpr.broadcaster.maxProcessingThreads` is set, a fixed pool is created instead. I guess that with a high enough number of threads set, it would similar to using a cached thread pool (one coming from `Executors.newCachedThreadPool()`).
