### ISSUE TITLE
Servlet 2.5 issues in Atmosphere 2.2.x and 2.3.x

### ISSUE THREAD

**Issue by cztorgar** [Atmosphere/atmosphere#1987]
I'm using Atmosphere on old web servers and I want it to default do long-polling.

In **AtmosphereResponse.java:416 getHeader()** method is called on the underlying HttpServletResponse but this method is present since **Servlet 3.0**...Thus this will throw an exception.

I tested it in **Tomcat 6.0.** and **Weblogic 10.3.6.** This part of code is only called when browser will send some specific headers. Firefox 38.x is not sending them and it is working without problems whereas Opera 43.x and IE 11.x are sending those headers, exception is thrown and server push is not working.

**Comment by gdrouet** [comment]
Can use reproducde this issue with the atmosphere-chat example?

**Comment by saikiran939** [comment]
@jfarcand Sorry for commenting on closed issue, this issue is still not complete. I tested atmosphere on weblogic 10.3.6. I am using AtmosphereRequestImpl.wrap(httpRequest) to convert http request to atmosphere request. AtmosphereRequestImpl has import statements for AsyncContext interface (part of 3.0) and I get class not found exception for java.async.AsyncContext.
