### ISSUE TITLE
@ManagedService unexpected behaviour with DeliverTo.DELIVER_TO.RESOURCE over long-polling

### ISSUE THREAD

**Issue by sachtilah** [Atmosphere/atmosphere#1994]
We trying to do this: 1: Client open connection ,GET method
                                 2: Client send json ,POST method
                                 3: We want to take some action which leads to modify json object and then send it back to the resource/client so client know if operation succeed or not.
                                 4.  Broadcast using another broadcaster 
 Lightweight version:
```java
        @Ready
	public void onReady(AtmosphereResource r) {}

	@Disconnect
	public void disconnected(AtmosphereResourceEvent r) {}

	@Post
	public void onPost(AtmosphereResource r) {}

	@Message(decoders = {JacksonDecoder.class}, encoders = {JacksonEncoder.class})
	@DeliverTo(DeliverTo.DELIVER_TO.RESOURCE)
	public Subscribe subscribeMessage(Subscribe message) {
		message.setProcessed(true);
		return message;
	}
```
With websocket  everything is working fine and response is written immediately back to the resource. When we  switch to long polling, we get  the response with next GET method. (Not with the one which is  opened, during the POST method.) No idea if DeliverTo.RESOURCE should lead to write entity into POST or into GET method.  Fix in IOUtils.deliver working but wrong resource is passed tho. A little hack is working but no idea if it has some side effects or if it could be done other way. 
ManagedAtmosphereHandler:
```java
public void onRequest(final AtmosphereResource resource) throws IOException {
.
.
before:
 MethodInfo.EncoderObject e = message(resource, body);
 if (e != null && e.encodedObject != null) {
     // wrong resource is passed tho
     IOUtils.deliver(new Managed(e.encodedObject), null, e.methodInfo.deliverTo, resource);
  }

changed to :
if (e != null && e.encodedObject != null) {
  if ( e.methodInfo.deliverTo == DeliverTo.DELIVER_TO.RESOURCE) {
    AtmosphereResource res = getHandshakeResource(resource.getRequest());
    IOUtils.deliver(new Managed(e.encodedObject), null, e.methodInfo.deliverTo, res);			
  }else {
    IOUtils.deliver(new Managed(e.encodedObject), null, e.methodInfo.deliverTo,   resource);					
  }
}
.
.
end of onRequest method
```
```java
@Inject
AtmosphereResourceFactory atmosphereResourceFactory;
	
private AtmosphereResource getHandshakeResource(AtmosphereRequest req) {
String uuid = (String) req.getAttribute(ApplicationConfig.SUSPENDED_ATMOSPHERE_RESOURCE_UUID);
		return atmosphereResourceFactory.find(uuid);
	}
```
Just a quick hack to test it. With this code its working fine and modified json is written back immediately using the opened GET request.

**Comment by jfarcand** [comment]
Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by jfarcand** [comment]
@sachtilah Do me a favor and do a pull request with your change. It seems indeed to fix the issue for other protocol than websocket.

**Comment by krskrs** [comment]
Hi,
I'd like to point out that this issue is strictly related with a conversation between me and jfarcand on the Google group:

https://groups.google.com/forum/#!topic/atmosphere-framework/0KEJeRlDUE8

and that:

```java
 if ( e.methodInfo.deliverTo == DeliverTo.DELIVER_TO.RESOURCE && !resource.transport().equals(AtmosphereResource.TRANSPORT.WEBSOCKET)) {
                    r = resourcesFactory.find(resource.uuid());
                }
```

here, the check for AtmosphereResource.TRANSPORT.WEBSOCKET might be wrong, since , although the underlying websocket connection is the same, the AtmoshpereResouce created when a WebSocket message is received is different from the original AtmosphereResource created on WebSocket handhsake, and they're also handled differently (the former has interceptors, while the latter hasn't. Don't know if this might have some side effects in some cases).

**Comment by jfarcand** [comment]
@krskrs Can you share a test case that demonstrate that the resource aren't containing the same? Interceptors are adding listeners, etc.

**Comment by krskrs** [comment]
Hi,
just a basic @ManagedService implementation, like the one provided in this issue should do.

However, I'll be adding some details. 

Please note that I'm not telling for sure that there will be actual issues with default interceptors, but just that the behavior is different, and I'm here just to discuss and analyze this with you.

For example, this code 

https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceLifecycleInterceptor.java#L145-L161

sets a listener on broadcast, which is then invoked when broadcasting on the original websocket AtmosphereResource (the one used for the handshake), but it's not set (and thus not called) on the AtmosphereResource associated with websocket messages, due to this check a few lines above:

https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceLifecycleInterceptor.java#L137

So, if you broadcast to the original resource, such listener will be called, otherwis it won't. Now the point is if this makes an actual difference.
 
The same can happen for user code too, if the user is not aware of this, and, for example, sets a listener on broadcast in the @get annotated method (which, as done in some official atmoshpere samples, can be used as a callback for new incoming connections).

**Comment by jfarcand** [comment]
@krskrs OK so that's kind of unrelated, e.g the way Atmosphere internal works doesn't need to work the way the application need to work. Can you explain setting a listener on a @get is related to this issue? Paste an example here. Thanks!!!!

**Comment by krskrs** [comment]
ok, I get your point, but what's your thought on the first part of my message, the one about the different behavior with the atmosphereresourceLifecycleInterceptor? such part is related with the framework itself.

**Comment by jfarcand** [comment]
@krskrs Why would you like to have the same Interceptor in that case? In one situation the connection is suspended and in the other it is not, hence why adding a listener we know will never be invoked? Keep in mind that if the resource transpost is polling or is a websocket message, it is not equal to websocket, streaming, sse or long-polling, hence the difference (it must be different because it is not the same).

**Comment by krskrs** [comment]
Hi jf,
again, I'm not stating there are issues for sure, just trying to make sure of this with your help.

So I'll try to put it from a different perspective:

https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceLifecycleInterceptor.java#L145-L161

See the code above, you're setting a listener on the broadcast event, and you're doing this also for Websocket clients (for their original atmosphereResource, the one which gets suspended at the handshake, and not for websocket messages) Correct? 

If this is all correct, the question is: for what broadcastings is this listener added in case of websocket clients? What is the purpose of this listener in case of websocket clients?

If you can confirm and clarify these points, I will draw my conclusions and try to explain myself better and/or further elaborate on this.

**Comment by jfarcand** [comment]
@krskrs It's time consuming to answer you so that will be my last answer, unless your company buy some professional services or you start helping this community by proposing pull request :-). For Websocket, under the hood all `AtmosphereResource` are sharing the same connection. That's the difference with other transport. So yes you are correct only the first one (the suspended) is used...but the second or third could have been used as well. I could have used a single `AtmosphereResource` for websocket using threads locals for representing `AtmosphereRequest` and `AtmosphereResponse`, which are different every time a new message is sent...but the complexity/concurency would have been little tricky to implement. but not impossible. 

Now keep in mind that adding listeners for nothing kill performance, increase memorry, etc.

**Comment by krskrs** [comment]
Hi jf I get your point :-) It's time consuming for me as well, also considering that I'm doing all of this just trying to help you to detect some subtle bugs or to make enhancements to the code. 

I already took time to explain and describe 2 subtle bugs, so I think I've already helped someway this community.

And also in this case I was just trying to do the same ;-) , but this time the situation is more complex and I thought that you might have helped me to quickly understand whether there's something which might have been improved / corrected or not (in the Atmosphere code), but I totally agree with you that this is becoming time consuming for both of us.

I appreciate that you'have been trying to describe and explain me some things, but mine were just questions made to elaborate more on my points, and to make myself clearer. I wasn't looking for help, if that wasn't clear. But I think it was.

So :-) I'd like to keep on helping, since we're using your project as well and, if it gets better, we will all benefit from the enhancements, but I don't want to waste neither our time nor mine.

So, after clarifying all of this (for example, that I can't buy professional support if I'm just trying to help with your project :-) ) I will try for a last time to stress what is the central point of all my reasoning. In case it might help, I'm also available for a text chat on skype or something alike, to clarify the issue.

So, this is the central point:

when suspending a websocket AtmoshpereResource you're attaching an onBroadacast listener to it. But why you're doing this? Is it really needed, if then you say that for websocket messages we can broadcast to the various AtmosphereResource which are created for every websocket messages and don't have such listener? (they haven't it, since they are not being suspended).

So 3 are the things:

```java
 r.addEventListener(new OnBroadcast() {
                @Override
                public void onBroadcast(AtmosphereResourceEvent event) {
                    switch (r.transport()) {
                        case JSONP:
                        case AJAX:
                        case LONG_POLLING:
                            break;
                        default:
                            try {
                                r.getResponse().flushBuffer();
                            } catch (IOException e) {
                                logger.trace("", e);
                            }
                            break;
                    }
                }
```

1) the onBroadcast Listener  is needed only for the firs websocket connection that is suspended
2) the onBroadcast Listener is never needed and can be avoided also for the 1st connection
3) the onBroadcast Listener is always needed when broadcasting to websocket connections, and so also the AtmosphereResources created for every websocket message should have it.




--
fc

**Comment by jfarcand** [comment]
@krskrs Try to remove and see what will happens and then submit a pull request :-) That's a good way to help!

**Comment by krskrs** [comment]
Hi @jfarcand .. :-) if you can't tell why this broadcast listener has been put here to execute this code  on broadcast:

```java
code r.getResponse().flushBuffer(); 
```
I'm afraid I won't be able to be of much help this time.

I might indeed remove it and try if websocket still works, but even if it did, there might still be some special cases which could break, and I wouldn't know it, since we don't know why it's here :-)

What I can tell for sure, is that in the fix you made you're not using this listener when broadcasting to websocket (because you are not retrieving/broadcasting to the original AtmosphereResource) and that was the main point of my considerations.

Nice conversation, by the way, and I will keep on reporting everything I might find ;-) as long as I will be developing with Atmosphere.

best,
fc

**Comment by jfarcand** [comment]
@krskrs test it with a debugger. That's the best way to learn why it is there :-)
