### ISSUE TITLE
long-polling dropping messages on multiple messages in a burst

### ISSUE THREAD

**Issue by jtbdevelopment** [Atmosphere/atmosphere#2063]
I have been experiencing some issues with atmosphere failing to publish messages when there is a burst of activity.  I cobbled my code together from docs and examples as there was nothing quite like it in the samples.  So it is quite possible I am doing something daft, but I can't see it.

I use atmosphere as part of a framework to write multi-player turn based games.  Each player subscribes to a dedicated unique channel ('/livefeed/{my id}') to receive updates via long-polling.  All updates are generated within the server (there are no writes from the client).  All updates are point to point to specific channels (i.e. if there is an update to a game with 5 players, each player is looked up and published to).  Because the server can be clustered, and different clients connected to different servers, each server does a lookup to see if the client is present on this server.

The code looks roughly like:
for each player in game {
  get broadcasterfactory
  broadcasterFactory.lookup( '/livefeed/{playerid}')
  if(!null) use it to publish 
  else this user is not on this server or not online at all
}

What I have found is if there is a burst of messages, while the client is processing the first message (not doing much and I did an experiment where I did even less) the lookup returns null.  If I put a pause/retry after 100ms loop in, the client is found on the 2nd attempt usually.  Is the lookup meant to fail if the client is already processing a message?  Am I completely misusing the framework?

The actual code for publishing is here (look at last function).  It does not have the loop/retry I added locally but you can see the basic shape of the code.
https://github.com/jtbdevelopment/core-games/blob/master/games-websocket/src/main/groovy/com/jtbdevelopment/games/websocket/AtmosphereListener.groovy
(broadcasterFactory.broadcasterFactory is a call to Universe.broadcasterFactory())

The channel is registered here:
https://github.com/jtbdevelopment/core-games/blob/master/games-websocket/src/main/groovy/com/jtbdevelopment/games/websocket/LiveFeedService.groovy

The client is atmosphere javascript here (again in my local version, I moved all processing inside an angular $timeout(function(){}); and no change.
https://github.com/jtbdevelopment/core-games-ui/blob/master/src/core-games-ui/services/liveGameFeed.js

Thank you for any help or pointers.

**Comment by jfarcand** [comment]
Hi, I don't have the cycle to closely look at your code, but can you describe why you don't do:
```java
broadcasterFactory.lookup( '/livefeed/{playerid}', true)
```
instead. That way you are guarantee the `Broadcaster` will always be created, event if two threads try to lookup at the same time.

**Comment by jtbdevelopment** [comment]
So the initial thought was, the servers are clustered, Player1 could be on server1, Player2 could be on server2, websocket wise.  As such, each server only tried to publish to connected players.  (One question would be - how long does an undelivered message hang around for?)

However, even trying this, it does not appear to work reliably.  I still miss messages on ui side and caught one of these in the server logs
WARN  o.atmosphere.cpr.DefaultBroadcaster - Duplicate resource bd17cc32-5a8e-4eab-9dd0-4d163a2c07b6. Could be caused by a dead connection not detected by your server. Replacing the old one with the fresh one

**Comment by jfarcand** [comment]
@jtbdevelopment Package a sample (or modify one of the sample) to reproduce. I'm extremely low on time right now and that's the only way I can help. Make sure the `UUIDBroadcasterCache`  is installed.

**Comment by jtbdevelopment** [comment]
Sure, I'll see if I can recreate using some of the chat samples - tho it may take me a bit to do.

re UUIDBroadcasterCache - that appears to be default and I am not overriding it

**Comment by jtbdevelopment** [comment]
OK I ginned up some examples based on your chat sample.  https://github.com/jtbdevelopment/atmosphere-samples

Fork of your samples project with most samples deleted and just the chat one left.  The chat default protocol is long-polling, not websocket.

The first change to both examples is 3 seconds after loading the pager, a chat bot is enabled which will spew counter to you.  The first one is in AutoChatter.java, the second in AutoChatterChannel.java.

1)  Problem 1 - dropped message when long-polling
---------------------------------------------------------------------
this is not one I experienced in my app, but found along the way of building example.
Run the app and load http://localhost:8080

this is your chat app with interceptors added and an auto chat bot.  3 seconds after you connect, it will start spewing numbers.  The javascript will stop once it detects a missed number.  At the checked in setting on my machine, I didn't have to go higher than a thousand before one gets missed.  Increase the frequency of messages and increase speed of missing one.  Change the sleep time in AutoChat.java to experiment.

using websocket protocol I went up to 10k without missing at high speeds.

however as I noted, this did not smell like the problem I was having. 

1)  Problem 2 - high speed dynamic channel
---------------------------------------------------------------------
So the one diff in my example is I used a dynamic path for each topic, similar to chat channel topics.  So I setup a second path called /channel/{alphanumeric} - see Channel.java, which is a clone of Chat.java but with         path = "/channel/{id: [a-zA-Z][a-zA-Z_0-9]*}" in the managed service.

The client and the auto chatter for this example are hard-coded to use channel 'testChannel' but atmosphere doesn't know this :)  This client DOES NOT stop subscribing when it misses a message.

this time go to http://localhost:8080/channel.html.

same setup - 3 seconds after loading, the auto chatter starts.  What you will see is the client is polling away missing a LOT of messages, while the server thinks it is publishing away. Neither one thinks they have a problem.  Sometimes they meet every few thousand messages.

This one looks a lot like the case I see.  Again, change the sleep to see varying levels of issues.  Again, no issues when protocol is websocket, only long-polling.

**Comment by jfarcand** [comment]
@jtbdevelopment I don't have the time to look at it for the next 3 weeks unfortunately. Are you using Jetty? If yes, that's might be an issue with Jetty itself.

**Comment by jtbdevelopment** [comment]
i use jetty for dev/automated testing and for this example, but tomcat in all other cases and behaviour appears consistent across platforms to me.

**Comment by CiaranSmith** [comment]
hi, 
We are getting the same issue as above with long-polling missing messages with a simple application.
Are there any known workarounds for this?

**Comment by jtbdevelopment** [comment]
I couldn't find one, nor could I figure out the issue.  In the end I figured out a configuration that allowed web sockets in almost all cases.

**Comment by CiaranSmith** [comment]
Cheers -  really appreciate the feedback on this. It corroborates what we are finding.

**Comment by saikiran939** [comment]
we have used UUIDBroadcasterCache as broadcaster cache, in our internal testing lots of messages got missed due to a bug in UUIDBroadcasterCache. In our test we published a burst of messages with long-polling transport.  The issue is due to the contention between addToCache() and retrieveFromCache() methods, due to the thread contention, the clientQueue can be overridden because of thread contention in addToCache() method (highlighted the contention):

 `private void addMessage(String broadcasterId, String clientId, CacheMessage message) {`
        `ClientQueue clientQueue = messages.get(clientId);`
        `if (clientQueue == null) {`
            `clientQueue = new ClientQueue();`
            `// Make sure the client is not in the process of being invalidated`
            `if (activeClients.get(clientId) != null) {`
               **` messages.put(clientId, clientQueue);`**
           ` } else {`
                `// The entry has been invalidated`
                `logger.debug("Client {} is no longer active. Not caching message {}}", clientId, message);`
                `return;`
            `}`
        `}`
       ` notifyAddCache(broadcasterId, message);`
       ` clientQueue.getQueue().offer(message);`
        `clientQueue.getIds().add(message.getId());`
    `}`

In retrieveCache() method, whenever client arrives, atmosphere gets all the messages from the cache and write to the client by removing the client queue (highlighted)

`public List<Object> retrieveFromCache(String broadcasterId, String uuid) {`
        `List<Object> result = new ArrayList<Object>();`

       `ClientQueue clientQueue;`
        `cacheCandidate(broadcasterId, uuid);`
        **`clientQueue = messages.remove(uuid);`**
        `ConcurrentLinkedQueue<CacheMessage> clientMessages;`
        `if (clientQueue != null) {`
            `clientMessages = clientQueue.getQueue();`

            `for (CacheMessage cacheMessage : clientMessages) {`
                `result.add(cacheMessage.getMessage());`
            `}`
        `}`

        `if (logger.isTraceEnabled()) {`
            `logger.trace("Retrieved for AtmosphereResource {} cached messages {}", uuid, result);`
            `logger.trace("Available cached message {}", messages);`
        `}`

        `return result;`
    `}`


Due to the contention between these methods few of the times the messages can be lost. We had to write our own implementation to fix this.

**Comment by jfarcand** [comment]
@saikiran939 Can you share your code?

**Comment by saikiran939** [comment]
the main problem arises that the client queue is removed whenever retrieveFromCache() is removed, and if there are many messages that are put into cache (usually this happens more in Long-polling), each thread which invokes addToCache() sees clientQueue as null, and they go ahead create a new clientQueue object - and put into 'messages' concurrent hashmap, if there is another thread doing the same thing, then the second thread overwrite with second queue, the first thread doesn't know this and it offers the message to the client queue that it has created previously because we have the reference to the queue.

What I did is to go away from client queue implementation (ClientQueue class) and to move the concurrent linked queue logic to outside to UUIDBroadcasterCache.  addToMessage() method would look like:

`if (activeClients.get(clientId) != null) {`			
				`clientQueue = new ConcurrentLinkedQueue<CacheMessage>();`
				`if (messages.putIfAbsent(clientId, clientQueue) == null) {`
					`logger.debug("new queue created for message %s, broadcaster %s for resource %s ",`
							`message.getMessage(), broadcasterId, clientId);`
				`}`


retrieveFromCache() is changed to: (not removing the queue from 'messages' map)

`ConcurrentLinkedQueue<CacheMessage> clientQueue = messages.get(uuid);`
`		CacheMessage message = null;`
`		List<Object> result = new ArrayList<Object>();`
`		if (clientQueue == null) {`
`			logger.debug("client queue is null (not yet created), hence returning back for broadcaster %s and uuid %s",`
`					broadcasterId, uuid);`
`			return result;`
`		}`
`		while ((message = clientQueue.poll()) != null) {`
`			result.add(message);`
`		}`
` return result;`


similarly, changed invalidateExpiredEntries() method to clear() the entries from queue, if the time has expired.

**Comment by jfarcand** [comment]
@saikiran939 I like it. Can you do a pull request (or a diif -u) so you get the credit?

**Comment by saikiran939** [comment]
Sure...

**Comment by jfarcand** [comment]
@saikiran939 Any update? Just do a pull request and I will cut a new release with it.

**Comment by saikiran939** [comment]
Sorry @jfarcand I was very much occupied. I will do it.

**Comment by saikiran939** [comment]
@jfarcand - opened pull request.

**Comment by bdevapatla** [comment]
@jfarcand @saikiran939 
I am still seeing this issue to some extent.  I am using ManagedService implementation of atmosphere. My scenario is as follows:

1) Client initially connects using long-poll. A 60 sec poll-interval is defined on AtmosphereRequest 
2) A no messages until 60 secs. The initial long-poll request is still not disconnected (essentially not replaced by a new request) 
3) At 90 secs, the following DEBUG message gets printed in my logs:

> DEBUG [Atmosphere-Scheduler-8] o.a.c.UUIDBroadcasterCache [UUIDBroadcasterCache.java:297] removed  client queue of size: 0 for client uuid bdba5c59-4145-4eb1-b099-f87cc7ff0d1a

4) I fire multiple updates to the client at this juncture.
5) Atmosphere only delivers one message to the client. 
6) Now, I see that previous longpoll request is replaced with a new one. 
7) From this point onward, when there is no update from server, longpoll request is replaced with a new one every 60 secs 

Any suggestions? I am not using latest version of atmosphere. 

Appreciate any help!

**Comment by saikiran939** [comment]
There could few factors which may impact delivery of messages:

1. Are you using tomcat 8? Then why use long polling ?

2. When you say only one message is received, atmosphere appends all the
messages into one message and separate them at client side. Did you clearly
see the message content ?

**Comment by bdevapatla** [comment]
@saikiran939 - Thanks for your reply.

1) Internal network settings are not allowing websocket connections. The fallback is long-polling 
2) I am not sure if I understand this. Multiple messages are broadcasted in a loop. I did not measure however the time gap between firing each message is in the order of mil.secs. 

I have actually tried using batching using following code and the issue persists.
`broadcaster.broadcast('[' + json + ']');`

I have opened [another issue](https://github.com/Atmosphere/atmosphere/issues/2308) with my observation on longpolling. I think the initial longpoll is a problem.

**Comment by saikiran939** [comment]
Did you try with latest version ? I have fixed a bug in long polling few
months back and I don't
Know if you have the fix on your environment.

On Dec 30, 2017 1:01 AM, "Bhanuprakash Devapatla" <notifications@github.com>
wrote:

@saikiran939 <https://github.com/saikiran939> - Thanks for your reply.

   1. Internal network settings are not allowing websocket connections. The
   fallback is long-polling
   2. I am not sure if I understand this. Multiple messages are broadcasted
   in a loop. I did not measure however the time gap between firing each
   message is in the order of mil.secs.

I have actually tried using batching using following code and the issue
persists.
broadcaster.broadcast('[' + json + ']');

I have opened another issue
<https://github.com/Atmosphere/atmosphere/issues/2308> with my observation
on longpolling. I think the initial longpoll is a problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Atmosphere/atmosphere/issues/2063#issuecomment-354490468>,
or mute the thread

**Comment by bdevapatla** [comment]
Hi @saikiran939  - Thanks for your reply.

I think we have your fix for long-polling from September 2016 (which is the same fix discussed in this thread). Was there another fix for long-polling recently? If so, can you point me to issue tracker link? 

I have tested my application using 2.4.14 version and long-polling seem to work fine without any issues so far. However I am not exactly what change in atmosphere framework has fixed the issue. Please help me understand this.

**Comment by saikiran939** [comment]
Not that I'm aware of. But may be some other fixes in latest release might
have fixed this.

On Jan 2, 2018 7:16 AM, "Bhanuprakash Devapatla" <notifications@github.com>
wrote:

Hi @saikiran939 <https://github.com/saikiran939> - Thanks for your reply.

I think we have your fix for long-polling from September 2016 (which is the
same fix discussed in this thread). Was there another fix for long-polling
recently? If so, can you point me to issue tracker link?

I have tested my application using 2.4.14 version and long-polling seem to
work fine without any issues so far. However I am not exactly what change
in atmosphere framework has fixed the issue. Please help me understand this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Atmosphere/atmosphere/issues/2063#issuecomment-354692088>,
or mute the thread

**Comment by bdevapatla** [comment]
Okay. Thanks @saikiran939 for your help

Hi @jfarcand - Can you please help understand recent fixes for long-polling?

**Comment by saikiran939** [comment]
@bdevapatla is it possible to to do a video recording and share with us here ?
