### ISSUE TITLE
Query string parameters are wrongly parsed as request headers

### ISSUE THREAD

**Issue by martin-g** [Atmosphere/atmosphere#2206]
At https://github.com/Atmosphere/atmosphere/blob/cd813ef1a641f621410ff47795d9d954694b4e65/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L2224-L2231 the query string parameters are stored as request headers.
Later at https://github.com/Atmosphere/atmosphere/blob/cd813ef1a641f621410ff47795d9d954694b4e65/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereRequestImpl.java#L349-L352 when a header needs to be read Atmosphere falls back to `b.headers` and returns the value of a query string parameter if the name matches.

I don't know whether there is a reason Atmosphere to do this but reading request parameters this way is wrong because the value is not url decoded.

**Comment by martin-g** [comment]
Ping!

**Comment by jfarcand** [comment]
@martin-g Pull request welcomed :-)

**Comment by martin-g** [comment]
What would be the proper fix?
IMO the headers should not contain the request parameters in a first place.

**Comment by jfarcand** [comment]
Agree, but that code is there since day one (back in 2009/2010) and changing it now would be quite risky. First steps would be to only allow Atmosphere's protocol value, e.g all `X-Atmosphere` and the one sent by the client should still be there as they are used by the framework. 

For backward compatibility, we should have a property that we can use to allow some query string to be placed as headers (added to the default Atmosphere;s one(

**Comment by jfarcand** [comment]
Won't fix
