### ISSUE TITLE
Getting responseBody as "X"

### ISSUE THREAD

**Issue by Nadia1989** [Atmosphere/atmosphere#2253]
No matter what message is being broadcasted by the broadcaster, the client is always receiving X. Any help will be appreciated.

{"status":200,"reasonPhrase":"OK","responseBody":"X","messages":["X"],"headers":[],"state":"messageReceived","transport":"websocket","error":null,"request":{"timeout":300000,"method":"GET","headers":{},"contentType":"application/json","callback":null,"url":"http://100.109.57.164:8081/MarketProject/chat?userId=58c3815f195b0206564f3360&latestPostId=58c3b1b7195be4b4b6a650f9","data":"","suspend":true,"maxRequest":-1,"reconnect":true,"maxStreamingLength":10000000,"lastIndex":0,"logLevel":"debug","requestCount":0,"fallbackMethod":"GET","fallbackTransport":"long-polling","transport":"websocket","webSocketImpl":null,"webSocketBinaryType":null,"dispatchUrl":null,"webSocketPathDelimiter":"@@","enableXDR":false,"rewriteURL":false,"attachHeadersAsQueryString":true,"executeCallbackBeforeReconnect":false,"readyState":0,"withCredentials":false,"trackMessageLength":true,"messageDelimiter":"|","connectTimeout":-1,"reconnectInterval":0,"dropHeaders":true,"uuid":"0","async":true,"shared":false,"readResponsesHeaders":false,"maxReconnectOnClose":5,"enableProtocol":true,"disableDisconnect":false,"pollingInterval":0,"heartbeat":{"client":null,"server":null},"ackInterval":0,"closeAsync":false,"reconnectOnServerError":true,"handleOnlineOffline":true,"mrequest":true,"firstMessage":false,"isOpen":true,"ctime":1489220225614,"id":67},"partialMessage":"","errorHandled":false,"closedByClientTimeout":false,"ffTryingReconnect":false}

--------
Server

public void onRequest(AtmosphereResource r) throws IOException {
    	broadcasterFactory.get(userId).broadcast("ABC");
    } 

Client
var request = { url: '<URL>',
					contentType : "application/json",
					logLevel : 'debug',
					transport : 'websocket' ,
					trackMessageLength : true,
					fallbackTransport: 'long-polling'
				};
				request.onOpen = function(response) {
					alert("text: "+'Atmosphere connected using ' + response.transport);
				};  
				request.onMessage = function (response) {
					
					console.log("response =>"+JSON.stringify(response));
                              }
}

**Comment by maddaliravi** [comment]
Hi ,

I am also a user  of this project. you get the message 'X' due to heartbeat Interceptor class that does server side broadcast to all clients .. probably every 30/60 seconds. you can check this class  'heartbeat Interceptor' for more details.

this heartbeat is to ensure web socket connection will be alive for a long period and to avoid closing those connections by proxy servers (they might close connection which are not active for a long time).


you can ignore the message 'X' and display all other messages to client.
or 
you can define a custom message instead of 'X' in heartbeat interceptor and ignore that on client side.
or 
try with disabling heat beat interceptor.. web.xml configuration.

**Comment by Nadia1989** [comment]
Thanks a lot for the response.
