### ISSUE TITLE
Extra memory allocations in TrackMessageSizeInterceptor

### ISSUE THREAD

**Issue by vbochenin** [Atmosphere/atmosphere#2364]
Extra memory allocation just to check if response contains only spaces.
It leads to allocation extra space in heap and more often `GC:Allocation failure` under heavy load

TrackMessageSizeInterceptor#Interceptor (line 149)

```
    String s = cb.toString(); // <-- will create extra char[] for payload

    if (s.trim().length() == 0) {
        return responseDraft;
    }
```

**Comment by jfarcand** [comment]
@vbochenin Pull request welcomed!

**Comment by slovdahl** [comment]
@jfarcand Not sure if it was intentional, but doesn't this change also mean that the whitespace padding added by `org.atmosphere.interceptor.PaddingAtmosphereInterceptor` will now have the length of the padding prefixed? Is that correctly handled by `atmosphere.js`? :thinking: Looking at https://github.com/Atmosphere/atmosphere-javascript/blob/b992083a6a927d26acbeffbae18963ad4f45c577/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1677 it doesn't look like that, but I haven't tested, so can't tell for sure.

I just noticed this locally while upgrading from 2.2.x to 2.7.2 and getting some failing tests :smile: We have some fairly strict tests for the protocol that caught this change.

**Comment by jfarcand** [comment]
@slovdahl Not sure about this one. I would need a test case to play with it, or some logging from your internal test

**Comment by slovdahl** [comment]
Yep, agreed. What would you think would be the proper way of solving it? :thinking: On the Java-side or on the JS-side?

**Comment by jfarcand** [comment]
I would fix it in the Java-side.

**Comment by slovdahl** [comment]
@jfarcand makes sense :+1: I opened #2452 for this purpose, please take a look when you have time.
